-- MySQL Script generated by MySQL Workbench
-- Thu Jun 14 00:52:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rm-e
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rm-e
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rm-e` DEFAULT CHARACTER SET utf8 ;
USE `rm-e` ;

-- -----------------------------------------------------
-- Table `rm-e`.`medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rm-e`.`medicamento` (
  `idmedicamento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `manipuladoura` VARCHAR(45) NULL,
  `vendido` VARCHAR(45) NULL,
  PRIMARY KEY (`idmedicamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rm-e`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rm-e`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `tipo` INT NOT NULL,
  `cpf` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rm-e`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rm-e`.`consulta` (
  `idconsulta` INT NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(45) NULL,
  `local` VARCHAR(45) NOT NULL,
  `hora` VARCHAR(45) NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idconsulta`, `usuario_idusuario`),
  INDEX `fk_consulta_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_consulta_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `rm-e`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rm-e`.`receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rm-e`.`receita` (
  `idreceita` INT NOT NULL AUTO_INCREMENT,
  `usada` TINYINT NULL DEFAULT 0,
  `cancelada` TINYINT NULL DEFAULT 0,
  `consulta_idconsulta` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `instrucao` VARCHAR(45) NULL,
  `horaVenda` VARCHAR(45) NULL,
  `dataVenda` VARCHAR(45) NULL,
  PRIMARY KEY (`idreceita`, `consulta_idconsulta`, `usuario_idusuario`),
  INDEX `fk_receita_consulta1_idx` (`consulta_idconsulta` ASC),
  INDEX `fk_receita_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_receita_consulta1`
    FOREIGN KEY (`consulta_idconsulta`)
    REFERENCES `rm-e`.`consulta` (`idconsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receita_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `rm-e`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rm-e`.`dosagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rm-e`.`dosagem` (
  `iddosagem` INT NOT NULL AUTO_INCREMENT,
  `meio` VARCHAR(45) NOT NULL,
  `frequencia` VARCHAR(45) NULL,
  `horario` VARCHAR(45) NULL,
  PRIMARY KEY (`iddosagem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rm-e`.`exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rm-e`.`exame` (
  `idexame` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `consulta_idconsulta` INT NOT NULL,
  PRIMARY KEY (`idexame`, `consulta_idconsulta`),
  INDEX `fk_exame_consulta1_idx` (`consulta_idconsulta` ASC),
  CONSTRAINT `fk_exame_consulta1`
    FOREIGN KEY (`consulta_idconsulta`)
    REFERENCES `rm-e`.`consulta` (`idconsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rm-e`.`receita_has_medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rm-e`.`receita_has_medicamento` (
  `receita_idreceita` INT NOT NULL,
  `medicamento_idmedicamento` INT NOT NULL,
  `vendido` TINYINT NULL DEFAULT 0,
  `dosagem_iddosagem` INT NOT NULL,
  PRIMARY KEY (`receita_idreceita`, `medicamento_idmedicamento`, `dosagem_iddosagem`),
  INDEX `fk_receita_has_medicamento_medicamento1_idx` (`medicamento_idmedicamento` ASC),
  INDEX `fk_receita_has_medicamento_receita1_idx` (`receita_idreceita` ASC),
  INDEX `fk_receita_has_medicamento_dosagem1_idx` (`dosagem_iddosagem` ASC),
  CONSTRAINT `fk_receita_has_medicamento_receita1`
    FOREIGN KEY (`receita_idreceita`)
    REFERENCES `rm-e`.`receita` (`idreceita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receita_has_medicamento_medicamento1`
    FOREIGN KEY (`medicamento_idmedicamento`)
    REFERENCES `rm-e`.`medicamento` (`idmedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_receita_has_medicamento_dosagem1`
    FOREIGN KEY (`dosagem_iddosagem`)
    REFERENCES `rm-e`.`dosagem` (`iddosagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
